# Generated by Django 3.2 on 2024-01-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_app', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
